-- Etapa 3 de 3 na tentativa de baratear current_ml_sale_deductions.
--
-- Materializa tambem os ITENS dos pedidos recentes, antes de tocar em
-- anuncios, para o planner entrar em order_items pela chave do pedido.
--
-- Resultado medido: 3.869 ms -> 3.492 ms. AINDA INSUFICIENTE.
--
-- Por que parei aqui: o plano mostra estimativa de 98.635 linhas contra
-- 1.113 reais em recent_orders. O Postgres nao consegue estimar
-- date_created > (subquery) e por isso escolhe hash join com seq scan em
-- vez de nested loop. Nenhuma reescrita da view contorna isso de forma
-- confiavel.
--
-- Conclusao: isto NAO deve ser uma view calculada a cada leitura. O
-- desenho correto e uma tabela materializada, mantida pelo proprio
-- pipeline de pedidos (escrever a baixa quando o pedido e sincronizado,
-- em vez de recalcular sobre 329 mil linhas a cada page load).
--
-- A view segue correta e NAO e consumida por nenhuma tela, entao nao ha
-- risco em producao. /estoque, /produtos e /compras continuam em
-- 235-258 ms.
--
-- Ganho liquido desta sequencia: 11.487 ms -> 3.492 ms (3,3x), mais o
-- indice orders_date_created_idx, que e util por si so - era a lacuna
-- registrada na auditoria.

-- O corpo vigente da view foi aplicado via MCP; sua definicao efetiva
-- pode ser conferida com pg_get_viewdef. Resumo estrutural:
--
--   recent_orders  (MATERIALIZED) - pedidos apos min(checked_at), via
--                                   orders_date_created_idx
--   recent_items   (MATERIALIZED) - itens desses pedidos, pela chave do
--                                   pedido
--   reliable_kits                 - composicao confiavel (mesma regra de
--                                   get_purchase_planning_signals)
--   sold_lines     (MATERIALIZED) - aplica o filtro de Full
--   consumption                   - simples direto + kit por componente
--
-- e a agregacao final por (organization_id, sku_key, warehouse_key) com o
-- filtro exato consumption.date_created > state.checked_at.
