-- Aplica a baixa materializada tambem ao planejamento de compra.
--
-- Aplicada em producao como 20260818132752, pela mesma tecnica de
-- reescrita da definicao vigente.
--
-- Aqui importa mais do que na tela de estoque: o disponivel entra
-- diretamente na formula (demanda no lead time + reserva - disponivel -
-- em transito). Sem a baixa, a sugestao subestima o que precisa comprar.
--
-- stock_by_sku agrega por sku_key somando os depositos, entao o join com
-- a matview por (sku_key, warehouse_key) e somado naturalmente.
--
-- Medido apos a mudanca: compras_page 241 ms, compras_summary 230 ms.
