-- ============================================================
-- Speed Bikers Gestão V2
--
-- Historical state snapshots for Mercado Livre offers.
--
-- One offer can represent:
--   1. a listing itself;
--   2. a specific variation of a listing.
--
-- We store only meaningful state changes.
-- ============================================================


-- ============================================================
-- 1. TABLE
-- ============================================================

create table public.ml_offer_state_snapshots (

  id uuid primary key
    default gen_random_uuid(),

  organization_id uuid not null,

  ml_account_id uuid not null,

  ml_listing_id uuid not null,

  ml_listing_variation_id uuid,

  product_id uuid,

  offer_scope text not null
    check (
      offer_scope in (
        'listing',
        'variation'
      )
    ),

  item_id text not null,

  variation_id text,

  seller_sku text,

  title text,

  listing_type_id text,

  status text,

  sub_status jsonb not null
    default '[]'::jsonb,

  price numeric(18, 2),

  available_quantity integer,

  sold_quantity integer,

  health numeric(8, 4),

  catalog_listing boolean,

  is_current boolean not null
    default true,

  /*
   * Timestamp reported by Mercado Livre
   * for the parent listing.
   *
   * We keep it as evidence, but it will NOT
   * by itself create a new snapshot.
   */
  ml_last_updated timestamptz,

  /*
   * When V2 observed this state.
   */
  captured_at timestamptz not null
    default now(),

  /*
   * Synchronization that produced this observation.
   *
   * Nullable because in the future snapshots may also
   * be generated by webhooks or other collectors.
   */
  source_sync_run_id uuid,

  source text not null
    default 'listings_sync'
    check (
      char_length(
        btrim(source)
      )
      between 1 and 60
    ),


  -- ----------------------------------------------------------
  -- RELATIONSHIPS
  -- ----------------------------------------------------------

  constraint ml_offer_snapshots_listing_fk
    foreign key (
      organization_id,
      ml_account_id,
      ml_listing_id
    )
    references public.ml_listings (
      organization_id,
      ml_account_id,
      id
    )
    on delete cascade,


  constraint ml_offer_snapshots_variation_fk
    foreign key (
      ml_listing_variation_id
    )
    references public.ml_listing_variations (
      id
    )
    on delete cascade,


  constraint ml_offer_snapshots_product_fk
    foreign key (
      organization_id,
      product_id
    )
    references public.products (
      organization_id,
      id
    )
    on delete set null,


  constraint ml_offer_snapshots_sync_run_fk
    foreign key (
      source_sync_run_id
    )
    references public.sync_runs (
      id
    )
    on delete set null,


  -- ----------------------------------------------------------
  -- SCOPE CONSISTENCY
  -- ----------------------------------------------------------

  constraint ml_offer_snapshots_scope_check
    check (

      (
        offer_scope = 'listing'

        and
        ml_listing_variation_id
          is null

        and
        variation_id
          is null
      )

      or

      (
        offer_scope = 'variation'

        and
        ml_listing_variation_id
          is not null

        and
        variation_id
          is not null
      )

    )
);


comment on table
public.ml_offer_state_snapshots
is
'Historical state changes of Mercado Livre listings and variations used for operational diagnosis.';


-- ============================================================
-- 2. INDEXES
-- ============================================================

create index
ml_offer_snapshots_listing_time_idx
on public.ml_offer_state_snapshots (
  ml_listing_id,
  captured_at desc
);


create index
ml_offer_snapshots_variation_time_idx
on public.ml_offer_state_snapshots (
  ml_listing_variation_id,
  captured_at desc
)
where
  ml_listing_variation_id
    is not null;


create index
ml_offer_snapshots_product_time_idx
on public.ml_offer_state_snapshots (
  product_id,
  captured_at desc
)
where
  product_id
    is not null;


create index
ml_offer_snapshots_account_time_idx
on public.ml_offer_state_snapshots (
  ml_account_id,
  captured_at desc
);


-- ============================================================
-- 3. RLS
-- ============================================================

alter table
public.ml_offer_state_snapshots
enable row level security;


revoke all
on public.ml_offer_state_snapshots
from anon;


revoke all
on public.ml_offer_state_snapshots
from authenticated;


grant select
on public.ml_offer_state_snapshots
to authenticated;


create policy
"users can view permitted offer snapshots"
on public.ml_offer_state_snapshots
for select
to authenticated

using (
  private.can_access_ml_account(
    ml_account_id
  )
);


-- ============================================================
-- 4. CAPTURE FUNCTION
--
-- Receives the listings processed by one sync batch.
--
-- Inserts:
--   - parent listing state;
--   - each current variation state.
--
-- A row is inserted ONLY when the meaningful business state
-- differs from the most recent snapshot.
-- ============================================================

create or replace function
public.capture_ml_offer_state_snapshots(
  target_listing_ids uuid[],
  target_sync_run_id uuid
)
returns integer

language plpgsql

security invoker

set search_path = ''

as $$

declare

  inserted_listings integer :=
    0;

  inserted_variations integer :=
    0;

begin

  if (
    target_listing_ids
      is null
    or
    cardinality(
      target_listing_ids
    ) = 0
  ) then

    return 0;

  end if;


  -- ==========================================================
  -- PARENT LISTINGS
  -- ==========================================================

  insert into
  public.ml_offer_state_snapshots (

    organization_id,

    ml_account_id,

    ml_listing_id,

    ml_listing_variation_id,

    product_id,

    offer_scope,

    item_id,

    variation_id,

    seller_sku,

    title,

    listing_type_id,

    status,

    sub_status,

    price,

    available_quantity,

    sold_quantity,

    health,

    catalog_listing,

    is_current,

    ml_last_updated,

    captured_at,

    source_sync_run_id,

    source

  )

  select

    listing.organization_id,

    listing.ml_account_id,

    listing.id,

    null,

    listing.product_id,

    'listing',

    listing.item_id,

    null,

    listing.seller_sku,

    listing.title,

    listing.listing_type_id,

    listing.status,

    listing.sub_status,

    listing.price,

    listing.available_quantity,

    listing.sold_quantity,

    listing.health,

    listing.catalog_listing,

    listing.is_current,

    listing.ml_last_updated,

    now(),

    target_sync_run_id,

    'listings_sync'

  from
    public.ml_listings
      as listing

  left join lateral (

    select
      snapshot.*

    from
      public.ml_offer_state_snapshots
        as snapshot

    where
      snapshot.ml_listing_id =
        listing.id

      and
      snapshot.offer_scope =
        'listing'

    order by
      snapshot.captured_at desc,
      snapshot.id desc

    limit 1

  ) as previous
    on true

  where
    listing.id =
      any(
        target_listing_ids
      )

    and (

      previous.id
        is null

      or

      row(

        previous.product_id,

        previous.seller_sku,

        previous.title,

        previous.listing_type_id,

        previous.status,

        previous.sub_status,

        previous.price,

        previous.available_quantity,

        previous.sold_quantity,

        previous.health,

        previous.catalog_listing,

        previous.is_current

      )

      is distinct from

      row(

        listing.product_id,

        listing.seller_sku,

        listing.title,

        listing.listing_type_id,

        listing.status,

        listing.sub_status,

        listing.price,

        listing.available_quantity,

        listing.sold_quantity,

        listing.health,

        listing.catalog_listing,

        listing.is_current

      )

    );


  get diagnostics
    inserted_listings =
      row_count;


  -- ==========================================================
  -- VARIATIONS
  --
  -- Variation-specific price/stock/SKU are preferred.
  -- Parent listing provides title/status/health/catalog.
  -- ==========================================================

  insert into
  public.ml_offer_state_snapshots (

    organization_id,

    ml_account_id,

    ml_listing_id,

    ml_listing_variation_id,

    product_id,

    offer_scope,

    item_id,

    variation_id,

    seller_sku,

    title,

    listing_type_id,

    status,

    sub_status,

    price,

    available_quantity,

    sold_quantity,

    health,

    catalog_listing,

    is_current,

    ml_last_updated,

    captured_at,

    source_sync_run_id,

    source

  )

  select

    listing.organization_id,

    listing.ml_account_id,

    listing.id,

    variation.id,

    coalesce(
      variation.product_id,
      listing.product_id
    ),

    'variation',

    listing.item_id,

    variation.variation_id,

    coalesce(
      variation.seller_sku,
      listing.seller_sku
    ),

    listing.title,

    listing.listing_type_id,

    listing.status,

    listing.sub_status,

    coalesce(
      variation.price,
      listing.price
    ),

    coalesce(
      variation.available_quantity,
      listing.available_quantity
    ),

    coalesce(
      variation.sold_quantity,
      listing.sold_quantity
    ),

    listing.health,

    listing.catalog_listing,

    (
      listing.is_current
      and
      variation.is_current
    ),

    listing.ml_last_updated,

    now(),

    target_sync_run_id,

    'listings_sync'

  from
    public.ml_listing_variations
      as variation

  join
    public.ml_listings
      as listing

    on
      listing.id =
        variation.ml_listing_id

  left join lateral (

    select
      snapshot.*

    from
      public.ml_offer_state_snapshots
        as snapshot

    where
      snapshot.ml_listing_variation_id =
        variation.id

      and
      snapshot.offer_scope =
        'variation'

    order by
      snapshot.captured_at desc,
      snapshot.id desc

    limit 1

  ) as previous
    on true

  where
    variation.ml_listing_id =
      any(
        target_listing_ids
      )

    and (

      previous.id
        is null

      or

      row(

        previous.product_id,

        previous.seller_sku,

        previous.title,

        previous.listing_type_id,

        previous.status,

        previous.sub_status,

        previous.price,

        previous.available_quantity,

        previous.sold_quantity,

        previous.health,

        previous.catalog_listing,

        previous.is_current

      )

      is distinct from

      row(

        coalesce(
          variation.product_id,
          listing.product_id
        ),

        coalesce(
          variation.seller_sku,
          listing.seller_sku
        ),

        listing.title,

        listing.listing_type_id,

        listing.status,

        listing.sub_status,

        coalesce(
          variation.price,
          listing.price
        ),

        coalesce(
          variation.available_quantity,
          listing.available_quantity
        ),

        coalesce(
          variation.sold_quantity,
          listing.sold_quantity
        ),

        listing.health,

        listing.catalog_listing,

        (
          listing.is_current
          and
          variation.is_current
        )

      )

    );


  get diagnostics
    inserted_variations =
      row_count;


  return
    inserted_listings
    +
    inserted_variations;

end;

$$;


-- ============================================================
-- 5. FUNCTION SECURITY
-- ============================================================

revoke all
on function
public.capture_ml_offer_state_snapshots(
  uuid[],
  uuid
)
from public;


revoke all
on function
public.capture_ml_offer_state_snapshots(
  uuid[],
  uuid
)
from anon;


revoke all
on function
public.capture_ml_offer_state_snapshots(
  uuid[],
  uuid
)
from authenticated;


grant execute
on function
public.capture_ml_offer_state_snapshots(
  uuid[],
  uuid
)
to service_role;
