-- Religa as baixas no estoque exibido de /estoque e /produtos, agora
-- lendo da matview stock_sale_deductions (84 linhas, indice unico) em vez
-- da view cara.
--
-- Aplicada em producao como 20260818132642, por reescrita da definicao
-- vigente de private.get_stock_product_signals via pg_get_functiondef,
-- para nao divergir do resto do corpo da funcao, que e extenso e nao muda.
--
-- A alteracao troca, no CTE stock_by_warehouse:
--
--   available_quantity = planilha + ajuste_nfe
--                        - baixa_por_venda + movimento_manual
--
-- Sinais: a venda REDUZ (quantity positiva na matview, subtraida); o
-- movimento manual JA vem com sinal (saida negativa), entao e somado.
--
-- Comparacao com a tentativa anterior, que usava a view direto
-- (20260818130029, revertida):
--
--   com a view      15.253 ms   (fora do ar)
--   com a matview      203 ms
--
-- Verificado: OffCrf-6 902-3=899, PA0018 87-2=85, G28A-Preto 842-2=840.
